### PR TITLE
Feature/ci

### PR DESCRIPTION
**Pull request by MortenRaeburn**
This is an implementation of a rudementary CI. It performs the following checks for every pull request:

- cargo check
- cargo fmt --check
- cargo test
- cargo clippy -- -D warnings

I also added a test which simply executes main() and fails is main panics.

### CODE REVIEW

**Comment by adamAndMath** [comment]
Could you `#[allow(...)]` on the unused fields for now? We can talk about removing them later.

**Comment by MortenRaeburn** [comment]
> Could you `#[allow(...)]` on the unused fields for now? We can talk about removing them later.

Yes, or we can just ignore the clippy errors for now. Thereby we won't forget to remove the allow statements later 🐒😁

**Comment by halvko** [comment]
Or we could add the allow statement, and create an issue to remind us to remove them

**Comment by adamAndMath** [comment]
Actually, I they're fixed after my `match` PR

**Pull request merged**
